#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform PushConstants{
    uint count;
} pc;

layout(set = 0, binding = 0) readonly buffer InputA{
    float values[];
} inputA;

layout(set = 0, binding = 1) readonly buffer InputB{
    float values[];
} inputB;

layout(set = 0, binding = 2) writeonly buffer Output{
    float values[];
} outputData;

void main(){
    const uint index = gl_GlobalInvocationID.x;
    if(index >= pc.count){
        return;
    }
    outputData.values[index] = inputA.values[index] + inputB.values[index];
}
